### ISSUE TITLE
Consider using Vitest instead of Jest

### ISSUE THREAD

**Issue by silentsilas** [kbysiec/vite-vanilla-ts-lib-starter#4]
This template was just what I needed, and made it really easy to get an importable TS library working. Thank you for this!

The only issue I ran into was getting Jest to see Vite environment variables, which I ended up just switching out with Vitest which has almost the same syntax and functionality as Jest. 

I believe it's just a matter of adding vitest as a dependency, then swapping 

```json
    "test": "jest --runInBand",
    "test:coverage": "jest --runInBand --coverage",
```

with

```json
    "test": "vitest",
    "test:coverage": "vitest run --coverage",
````

And importing the Jest-like functions from Vitest in your tests.

```javascript
import { describe, it, expect } from "vitest";
```

I think the only downside is that the speed gains from --runInBand will be lost. Vitest has a similar `--threads` option, but it requires the user to provide isolation in tests themselves, which I'm not too sure what that entails.

Edit: And to clarify what this would help fix, with Vitest I can now create a `.env.local` file or `.env.test.local` file with `VITE_TEST_SECRET='some_secret_i_dont_want_to_commit_in_my_repo'` and the tests can access it via `import.meta.env.VITE_TEST_SECRET`.

**Comment by kbysiec** [comment]
@silentsilas,

apologies for such a delay in response. It is done - template from now use Vitest instead of Jest for testing.
This was a good idea, thanks!

Regards,
Kamil
