### ISSUE TITLE
Wrong output name

### ISSUE THREAD

**Issue by darkdread** [kbysiec/vite-vanilla-ts-lib-starter#8]
The output of the generated .js files are based on the package.json name. This example template, when built, will not be usable by other consumers because the file name referenced does not exist. Although it probably won't affect template users, I still feel the need to address this issue.

https://github.com/kbysiec/vite-vanilla-ts-lib-starter/blob/564cbbcb8908a25fc5654bed1949d4577d251146/package.json#L2-L5

**Comment by kbysiec** [comment]
You have to rename them to the name you need. I cannot see the problem honestly...

**Comment by darkdread** [comment]
> 

My point is the name of the package and the name of the exports should match for completeness sake, because that is the intended design in this template.

**Comment by olitreadwell** [comment]
@darkdread does this fix what you're talking about? 

@kbysiec

**Comment by kbysiec** [comment]
@olitreadwell Thank you for PR! It was so simple but I couldn't notice it for such a long time 🙂

@darkdread Filepaths are already updated, thank you for pointing this out.
